services:

  oar-service:
    ports:
      - 8080:8080
    environment:
      PG_HOST: "oar-postgres"
    healthcheck:
      test: 'wget --no-verbose --tries=1 --spider http://0.0.0.0:8080/health || exit 1'
      interval: 3s
      retries: 5
      start_period: 3s
      timeout: 5s
    depends_on:
      oar-postgres:
        condition: service_healthy

  wait-for-db:  # If you run this, it is designed to just build an arbitrary container to wait for pg startup
    image: hello-world
    depends_on:
      oar-postgres:
        condition: service_healthy

  oar-postgres:
    image: postgres:15.1-alpine
    restart: always
    container_name: oar-postgres
    environment:
      - POSTGRES_DB=oar
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - $PWD/dbData:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  oar-enrich-ui:
    ports:
      - 80:3000
    depends_on:
      oar-postgres:
        condition: service_healthy

      oar-service:
        condition: service_healthy
