services:
  oar-service:
    ports:
      - 8080:8080

  oar-postgres:
    image: postgres:15.1-alpine
    restart: always
    container_name: oar-postgres
    environment:
      - POSTGRES_DB=oar
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - $PWD/dbData:/var/lib/postgresql/data
