name: Service - Run Unit Tests

on:
  pull_request:
    paths:
      - service/**
    branches:
      - main
  workflow_dispatch:

jobs:
  service-unit-tests:

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install pSQL (Needed for DB setup)
        run: |
          sudo apt-get update
          sudo apt-get install --yes --no-install-recommends postgresql-client

      - name: Start local DB
        run: make db

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Install dependencies
        shell: bash
        run: cd service; go get -d -v

      - name: Build binary
        shell: bash
        run: cd service; CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo .

      - name: Test
        run: make test-service