name: Build Binary and Test

on:
  push:
    paths:
      - service/**
  pull_request:
    types: [opened, edited]
    paths:
      - service/**
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-test:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Start local DB
        run: make db

      - name: Install pSQL
        run: |
          sudo apt-get update
          sudo apt-get install --yes --no-install-recommends postgresql-client

      - name: Run init DB script
        run: PGPASSWORD=postgres psql -h localhost:5432 -U postgres -d oar -f scripts/sql/init_postgres.sql

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Install dependencies
        shell: bash
        run: cd service; go get -d -v

      - name: Build binary
        shell: bash
        run: cd service; CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo .

      - name: Test
        run: make test-service